### ISSUE TITLE
Can't access structure.stl file

### ISSUE THREAD

**Issue by sourabhacharya** [Danfoa/invite-robotics#10]
I see error 404 when trying to download structure.stl file from readme tutorial (https://github.com/Danfoa/invite-robotics/wiki/Tutorial---Simulation-Scene-Objects):

structure.stl file is not available at this URL:
https://github.com/Danfoa/invite-robotics/blob/developmental/invite_motoman_moveit_config/scenes/STL/structure.stl

Could please update it? Thanks!

**Comment by Danfoa** [comment]
@sourabhacharya Just updated the link.

In the following weeks, this tutorial will be complemented with more useful information.
